[variables]
    NIXPACKS_PHP_EXTENSIONS = 'bcmath, ctype, curl, dom, exif, fileinfo, filter, gd, hash, iconv, intl, mbstring, openssl, pcre, pdo, pdo_mysql, pdo_pgsql, session, tokenizer, xml, zip'

[start]
    cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
